<ul class="nav nav-tabs filter-tabs mb-3" id="applicantFilterTabs" role="tablist">
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'all' ? 'active' : '' ?>" <?= $selectedFilter === 'all' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'all', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="all" role="tab" aria-selected="<?= $selectedFilter === 'all' ? 'true' : 'false' ?>">All</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'new' ? 'active' : '' ?>" <?= $selectedFilter === 'new' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'new', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="new" role="tab" aria-selected="<?= $selectedFilter === 'new' ? 'true' : 'false' ?>">New</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'documents-issue' ? 'active' : '' ?>" <?= $selectedFilter === 'documents-issue' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'documents-issue', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="documents-issue" role="tab" aria-selected="<?= $selectedFilter === 'documents-issue' ? 'true' : 'false' ?>">Documents Issue</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'under-processing' ? 'active' : '' ?>" <?= $selectedFilter === 'under-processing' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'under-processing', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="under-processing" role="tab" aria-selected="<?= $selectedFilter === 'under-processing' ? 'true' : 'false' ?>">Under Processing</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'for-action' ? 'active' : '' ?>" <?= $selectedFilter === 'for-action' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'for-action', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="for-action" role="tab" aria-selected="<?= $selectedFilter === 'for-action' ? 'true' : 'false' ?>">For Action</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'approved' ? 'active' : '' ?>" <?= $selectedFilter === 'approved' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'approved', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="approved" role="tab" aria-selected="<?= $selectedFilter === 'approved' ? 'true' : 'false' ?>">Approved</a></li>
    <li class="nav-item" role="presentation"><a class="nav-link <?= $selectedFilter === 'completed' ? 'active' : '' ?>" <?= $selectedFilter === 'completed' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildPassportUrl(['filter' => 'completed', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="completed" role="tab" aria-selected="<?= $selectedFilter === 'completed' ? 'true' : 'false' ?>">Completed</a></li>
</ul>
