<ul class="nav nav-tabs mb-3" id="aeStatusTabs" role="tablist">
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'all' ? 'active' : '' ?>" <?= $selectedTab === 'all' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'all', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="all" role="tab" aria-selected="<?= $selectedTab === 'all' ? 'true' : 'false' ?>">All</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'new' ? 'active' : '' ?>" <?= $selectedTab === 'new' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'new', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="new" role="tab" aria-selected="<?= $selectedTab === 'new' ? 'true' : 'false' ?>">New</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'for-follow-up' ? 'active' : '' ?>" <?= $selectedTab === 'for-follow-up' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'for-follow-up', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="for-follow-up" role="tab" aria-selected="<?= $selectedTab === 'for-follow-up' ? 'true' : 'false' ?>">For Follow-up</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'ongoing' ? 'active' : '' ?>" <?= $selectedTab === 'ongoing' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'ongoing', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="ongoing" role="tab" aria-selected="<?= $selectedTab === 'ongoing' ? 'true' : 'false' ?>">Ongoing</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'payment-issues' ? 'active' : '' ?>" <?= $selectedTab === 'payment-issues' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'payment-issues', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="payment-issues" role="tab" aria-selected="<?= $selectedTab === 'payment-issues' ? 'true' : 'false' ?>">Payment Issues</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'cancel-booking' ? 'active' : '' ?>" <?= $selectedTab === 'cancel-booking' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'cancel-booking', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="cancel-booking" role="tab" aria-selected="<?= $selectedTab === 'cancel-booking' ? 'true' : 'false' ?>">Cancel Booking</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'finished' ? 'active' : '' ?>" <?= $selectedTab === 'finished' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'finished', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="finished" role="tab" aria-selected="<?= $selectedTab === 'finished' ? 'true' : 'false' ?>">Finished</a></li>
    <li class="nav-item"><a class="nav-link <?= $selectedTab === 'refund' ? 'active' : '' ?>" <?= $selectedTab === 'refund' ? 'aria-current="page"' : '' ?> href="<?= htmlspecialchars($buildAccountExecutiveUrl(['tab' => 'refund', 'page' => 1]), ENT_QUOTES, 'UTF-8') ?>" data-filter="refund" role="tab" aria-selected="<?= $selectedTab === 'refund' ? 'true' : 'false' ?>">Refund</a></li>
</ul>
